#Server Port
server:
  port: 8090
  
#db configuration

#Hibernate Config
spring:
  jpa:
    hibernate:
      ddl-auto: update
      
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/blogging_application
    username: root
    password: admin
    
project:
  image: images/  